import { Category } from '../types';

/** Maps lowercase item keywords → grocery category */
export const CATEGORY_MAP: Record<string, Category> = {
  // Produce
  apple: 'produce',
  apples: 'produce',
  banana: 'produce',
  bananas: 'produce',
  orange: 'produce',
  oranges: 'produce',
  lemon: 'produce',
  lemons: 'produce',
  lime: 'produce',
  limes: 'produce',
  mango: 'produce',
  mangoes: 'produce',
  grape: 'produce',
  grapes: 'produce',
  strawberry: 'produce',
  strawberries: 'produce',
  blueberry: 'produce',
  blueberries: 'produce',
  avocado: 'produce',
  avocados: 'produce',
  tomato: 'produce',
  tomatoes: 'produce',
  potato: 'produce',
  potatoes: 'produce',
  onion: 'produce',
  onions: 'produce',
  garlic: 'produce',
  carrot: 'produce',
  carrots: 'produce',
  spinach: 'produce',
  lettuce: 'produce',
  kale: 'produce',
  broccoli: 'produce',
  cauliflower: 'produce',
  cucumber: 'produce',
  cucumbers: 'produce',
  celery: 'produce',
  corn: 'produce',
  peas: 'produce',
  ginger: 'produce',
  herbs: 'produce',
  cilantro: 'produce',
  parsley: 'produce',
  basil: 'produce',
  mushroom: 'produce',
  mushrooms: 'produce',
  pepper: 'produce',
  peppers: 'produce',
  zucchini: 'produce',
  asparagus: 'produce',

  // Dairy & Eggs
  milk: 'dairy',
  'oat milk': 'dairy',
  'almond milk': 'dairy',
  'soy milk': 'dairy',
  'coconut milk': 'dairy',
  'skim milk': 'dairy',
  'whole milk': 'dairy',
  butter: 'dairy',
  cheese: 'dairy',
  cheddar: 'dairy',
  mozzarella: 'dairy',
  parmesan: 'dairy',
  yogurt: 'dairy',
  'greek yogurt': 'dairy',
  cream: 'dairy',
  'heavy cream': 'dairy',
  'sour cream': 'dairy',
  'cream cheese': 'dairy',
  eggs: 'dairy',
  egg: 'dairy',
  'free range eggs': 'dairy',
  'almond milk': 'dairy',

  // Meat & Seafood
  chicken: 'meat',
  beef: 'meat',
  pork: 'meat',
  lamb: 'meat',
  turkey: 'meat',
  fish: 'meat',
  salmon: 'meat',
  tuna: 'meat',
  shrimp: 'meat',
  bacon: 'meat',
  sausage: 'meat',
  'ground beef': 'meat',
  'chicken breast': 'meat',
  steak: 'meat',

  // Bakery
  bread: 'bakery',
  'sourdough bread': 'bakery',
  'whole wheat bread': 'bakery',
  bagel: 'bakery',
  bagels: 'bakery',
  muffin: 'bakery',
  muffins: 'bakery',
  croissant: 'bakery',
  croissants: 'bakery',
  rolls: 'bakery',
  buns: 'bakery',
  cake: 'bakery',
  cookies: 'bakery',
  crackers: 'bakery',
  tortilla: 'bakery',
  tortillas: 'bakery',
  pita: 'bakery',
  naan: 'bakery',

  // Frozen
  'frozen pizza': 'frozen',
  'ice cream': 'frozen',
  'frozen vegetables': 'frozen',
  'frozen fruit': 'frozen',
  'frozen meals': 'frozen',
  'frozen chicken': 'frozen',
  'frozen fish': 'frozen',
  'frozen avocado': 'frozen',
  'frozen peas': 'frozen',
  'frozen corn': 'frozen',

  // Beverages
  water: 'beverages',
  'sparkling water': 'beverages',
  juice: 'beverages',
  'orange juice': 'beverages',
  coffee: 'beverages',
  tea: 'beverages',
  soda: 'beverages',
  'sparkling water': 'beverages',
  beer: 'beverages',
  wine: 'beverages',
  kombucha: 'beverages',
  smoothie: 'beverages',
  'energy drink': 'beverages',
  lemonade: 'beverages',

  // Snacks
  chips: 'snacks',
  'potato chips': 'snacks',
  popcorn: 'snacks',
  pretzels: 'snacks',
  nuts: 'snacks',
  almonds: 'snacks',
  cashews: 'snacks',
  peanuts: 'snacks',
  'trail mix': 'snacks',
  'granola bar': 'snacks',
  'granola bars': 'snacks',
  chocolate: 'snacks',
  candy: 'snacks',
  gummy: 'snacks',
  popcorn: 'snacks',
  crackers: 'snacks',
  hummus: 'snacks',
  salsa: 'snacks',
  guacamole: 'snacks',
  cereal: 'snacks',
  granola: 'snacks',
  oatmeal: 'snacks',
  oats: 'snacks',

  // Household
  'dish soap': 'household',
  'laundry detergent': 'household',
  'paper towels': 'household',
  'toilet paper': 'household',
  tissues: 'household',
  sponges: 'household',
  'trash bags': 'household',
  'zip lock bags': 'household',
  'plastic bags': 'household',
  bleach: 'household',
  'all-purpose cleaner': 'household',
  'window cleaner': 'household',
  'aluminum foil': 'household',
  'plastic wrap': 'household',
  'baking soda': 'household',
  vinegar: 'household',

  // Personal Care
  shampoo: 'personal-care',
  conditioner: 'personal-care',
  soap: 'personal-care',
  'body wash': 'personal-care',
  toothpaste: 'personal-care',
  toothbrush: 'personal-care',
  'dental floss': 'personal-care',
  deodorant: 'personal-care',
  'face wash': 'personal-care',
  moisturizer: 'personal-care',
  sunscreen: 'personal-care',
  razors: 'personal-care',
  'hand sanitizer': 'personal-care',
  lotion: 'personal-care',
  bandages: 'personal-care',
  'pain reliever': 'personal-care',
  vitamins: 'personal-care',
};

/**
 * Returns the category for a given item name.
 * Checks multi-word phrases first, then single-word keywords.
 */
export function getCategory(itemName: string): Category {
  const lower = itemName.toLowerCase().trim();

  // Try exact match first
  if (CATEGORY_MAP[lower]) return CATEGORY_MAP[lower];

  // Try multi-word prefix match (longest first)
  const entries = Object.entries(CATEGORY_MAP).sort(
    ([a], [b]) => b.length - a.length
  );
  for (const [key, cat] of entries) {
    if (lower.includes(key)) return cat;
  }

  return 'other';
}
