import { Product } from '../types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Organic Hass Avocados (Bag of 4)',
    brand: 'Whole Foods',
    price: 4.99,
    originalPrice: 6.99,
    category: 'produce',
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['organic', 'produce', 'avocado', 'fresh'],
  },
  {
    id: 'p2',
    name: 'Single Large Organic Avocado',
    brand: "Local Farmer's Market",
    price: 1.5,
    category: 'produce',
    imageUrl: 'https://images.unsplash.com/photo-1601039641847-7857b994d704?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['organic', 'produce', 'avocado', 'local', 'fresh'],
  },
  {
    id: 'p3',
    name: 'Organic Avocado Oil Mayo',
    brand: 'Primal Kitchen · 12oz',
    price: 4.89,
    originalPrice: 5.49,
    category: 'snacks',
    imageUrl: 'https://images.unsplash.com/photo-1574781330855-d0db8cc6a79c?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['organic', 'mayo', 'avocado', 'condiment', 'gluten-free'],
  },
  {
    id: 'p4',
    name: 'Frozen Organic Avocado Halves',
    brand: "Trader Joe's",
    price: 3.49,
    category: 'frozen',
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=300&h=300&fit=crop',
    inStock: false,
    tags: ['organic', 'frozen', 'avocado'],
  },
  {
    id: 'p5',
    name: 'Organic Baby Spinach (5oz)',
    brand: 'Earthbound Farm',
    price: 3.99,
    category: 'produce',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['organic', 'spinach', 'produce', 'greens', 'salad'],
  },
  {
    id: 'p6',
    name: 'Oat Milk Original (64oz)',
    brand: 'Oatly',
    price: 5.49,
    category: 'dairy',
    imageUrl: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['oat milk', 'dairy-free', 'vegan', 'beverages'],
  },
  {
    id: 'p7',
    name: 'Organic Almond Milk Unsweetened',
    brand: 'Califia Farms',
    price: 4.29,
    category: 'dairy',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['almond milk', 'dairy-free', 'vegan', 'organic'],
  },
  {
    id: 'p8',
    name: 'Free Range Large Eggs (1 Dozen)',
    brand: 'Vital Farms',
    price: 6.99,
    category: 'dairy',
    imageUrl: 'https://images.unsplash.com/photo-1582169296194-e4d644c48063?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['eggs', 'free range', 'dairy', 'protein'],
  },
  {
    id: 'p9',
    name: 'Sourdough Bread Loaf',
    brand: 'Tartine Bakery',
    price: 8.99,
    category: 'bakery',
    imageUrl: 'https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['bread', 'sourdough', 'bakery', 'fresh'],
  },
  {
    id: 'p10',
    name: 'Whole Wheat Bread',
    brand: 'Dave\'s Killer Bread',
    price: 5.99,
    category: 'bakery',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['bread', 'whole wheat', 'bakery', 'organic'],
  },
  {
    id: 'p11',
    name: 'Organic Whole Milk (1 Gallon)',
    brand: 'Horizon Organic',
    price: 7.49,
    category: 'dairy',
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['milk', 'dairy', 'organic', 'whole milk'],
  },
  {
    id: 'p12',
    name: 'Greek Yogurt Plain (32oz)',
    brand: 'Chobani',
    price: 5.29,
    category: 'dairy',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['yogurt', 'greek yogurt', 'dairy', 'protein'],
  },
  {
    id: 'p13',
    name: 'Atlantic Salmon Fillet',
    brand: 'Whole Foods Seafood',
    price: 12.99,
    originalPrice: 15.99,
    category: 'meat',
    imageUrl: 'https://images.unsplash.com/photo-1574781330855-d0db8cc6a79c?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['salmon', 'seafood', 'fish', 'protein', 'omega-3'],
  },
  {
    id: 'p14',
    name: 'Organic Chicken Breast (1lb)',
    brand: 'Smart Chicken',
    price: 8.99,
    category: 'meat',
    imageUrl: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['chicken', 'meat', 'protein', 'organic'],
  },
  {
    id: 'p15',
    name: 'Honeycrisp Apples (3lb Bag)',
    brand: 'Local Orchard',
    price: 5.99,
    category: 'produce',
    imageUrl: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['apples', 'produce', 'fruit', 'fresh', 'honeycrisp'],
  },
  {
    id: 'p16',
    name: 'Organic Blueberries (6oz)',
    brand: 'Driscoll\'s',
    price: 3.99,
    category: 'produce',
    imageUrl: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['blueberries', 'produce', 'fruit', 'organic', 'fresh'],
  },
  {
    id: 'p17',
    name: 'Sparkling Water Variety Pack (12pk)',
    brand: 'LaCroix',
    price: 6.99,
    category: 'beverages',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['sparkling water', 'beverages', 'water', 'zero sugar'],
  },
  {
    id: 'p18',
    name: 'Cold Brew Coffee Concentrate',
    brand: 'Chameleon',
    price: 9.99,
    originalPrice: 12.99,
    category: 'beverages',
    imageUrl: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['coffee', 'cold brew', 'beverages', 'caffeine'],
  },
  {
    id: 'p19',
    name: 'Organic Kombucha GT\'s Original',
    brand: "GT's Living Foods",
    price: 3.79,
    category: 'beverages',
    imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['kombucha', 'beverages', 'probiotic', 'organic'],
  },
  {
    id: 'p20',
    name: 'Kettle Brand Sea Salt Chips (8oz)',
    brand: 'Kettle Brand',
    price: 4.49,
    category: 'snacks',
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['chips', 'snacks', 'potato chips', 'sea salt'],
  },
  {
    id: 'p21',
    name: 'KIND Dark Chocolate Nuts Bar (6pk)',
    brand: 'KIND',
    price: 7.99,
    category: 'snacks',
    imageUrl: 'https://images.unsplash.com/photo-1575377222312-dd1a63a51638?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['granola bar', 'snacks', 'chocolate', 'nuts', 'gluten-free'],
  },
  {
    id: 'p22',
    name: 'Organic Baby Carrots (1lb)',
    brand: 'Bolthouse Farms',
    price: 2.49,
    category: 'produce',
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['carrots', 'produce', 'vegetables', 'organic'],
  },
  {
    id: 'p23',
    name: 'Sabra Classic Hummus (17oz)',
    brand: 'Sabra',
    price: 5.49,
    originalPrice: 6.99,
    category: 'snacks',
    imageUrl: 'https://images.unsplash.com/photo-1577805947697-89e18249d767?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['hummus', 'snacks', 'dip', 'vegan'],
  },
  {
    id: 'p24',
    name: 'Unsalted Almonds (1lb)',
    brand: 'Blue Diamond',
    price: 8.99,
    category: 'snacks',
    imageUrl: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['almonds', 'nuts', 'snacks', 'protein'],
  },
  {
    id: 'p25',
    name: 'Extra Virgin Olive Oil (16.9oz)',
    brand: 'California Olive Ranch',
    price: 10.99,
    originalPrice: 13.99,
    category: 'household',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['olive oil', 'cooking', 'organic'],
  },
  {
    id: 'p26',
    name: 'Organic Quinoa (16oz)',
    brand: 'Ancient Harvest',
    price: 5.99,
    category: 'snacks',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['quinoa', 'grain', 'organic', 'protein', 'gluten-free'],
  },
  {
    id: 'p27',
    name: 'Fresh Broccoli Crown',
    brand: 'Fresh Market',
    price: 2.99,
    category: 'produce',
    imageUrl: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['broccoli', 'produce', 'vegetables', 'fresh'],
  },
  {
    id: 'p28',
    name: 'Sharp Cheddar Cheese Block (8oz)',
    brand: 'Tillamook',
    price: 5.99,
    category: 'dairy',
    imageUrl: 'https://images.unsplash.com/photo-1618164435735-413d3b066c9a?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['cheese', 'cheddar', 'dairy', 'sharp'],
  },
  {
    id: 'p29',
    name: 'Organic Rolled Oats (18oz)',
    brand: 'Bob\'s Red Mill',
    price: 4.49,
    category: 'snacks',
    imageUrl: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['oats', 'oatmeal', 'breakfast', 'organic', 'gluten-free'],
  },
  {
    id: 'p30',
    name: 'Unsweetened Coconut Milk (13.5oz)',
    brand: "Thai Kitchen",
    price: 2.99,
    category: 'dairy',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['coconut milk', 'dairy-free', 'vegan', 'cooking'],
  },
  {
    id: 'p31',
    name: 'Organic Strawberries (1lb)',
    brand: "Driscoll's",
    price: 4.99,
    category: 'produce',
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['strawberries', 'produce', 'fruit', 'organic', 'fresh'],
  },
  {
    id: 'p32',
    name: 'Lentil Pasta Rotini (8oz)',
    brand: 'Banza',
    price: 3.49,
    category: 'snacks',
    imageUrl: 'https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['pasta', 'lentil', 'gluten-free', 'protein'],
  },
  {
    id: 'p33',
    name: 'Organic Green Tea (20 bags)',
    brand: 'Yogi Tea',
    price: 5.49,
    category: 'beverages',
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['tea', 'green tea', 'beverages', 'organic'],
  },
  {
    id: 'p34',
    name: 'Free Range Turkey Bacon (12oz)',
    brand: 'Applegate',
    price: 7.99,
    category: 'meat',
    imageUrl: 'https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['turkey bacon', 'bacon', 'meat', 'free range'],
  },
  {
    id: 'p35',
    name: 'Organic Yellow Onions (3lb)',
    brand: 'Fresh Market',
    price: 2.99,
    category: 'produce',
    imageUrl: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['onions', 'produce', 'vegetables', 'organic'],
  },
  {
    id: 'p36',
    name: 'Almond Butter Creamy (16oz)',
    brand: 'Justin\'s',
    price: 10.99,
    originalPrice: 12.99,
    category: 'snacks',
    imageUrl: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['almond butter', 'nut butter', 'snacks', 'protein', 'vegan'],
  },
  {
    id: 'p37',
    name: 'Organic Tomatoes on Vine (1lb)',
    brand: 'Sunset Farms',
    price: 3.49,
    category: 'produce',
    imageUrl: 'https://images.unsplash.com/photo-1546094096-0df4bcabd337?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['tomatoes', 'produce', 'vegetables', 'organic', 'fresh'],
  },
  {
    id: 'p38',
    name: 'Sriracha Hot Sauce (17oz)',
    brand: 'Huy Fong',
    price: 4.49,
    category: 'snacks',
    imageUrl: 'https://images.unsplash.com/photo-1608500218889-b3705ead04ba?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['hot sauce', 'condiment', 'spicy'],
  },
  {
    id: 'p39',
    name: 'Organic Frozen Edamame (14oz)',
    brand: "Trader Joe's",
    price: 2.49,
    category: 'frozen',
    imageUrl: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['edamame', 'frozen', 'protein', 'organic', 'vegan'],
  },
  {
    id: 'p40',
    name: 'Sparkling Orange Juice (4pk)',
    brand: 'San Pellegrino',
    price: 6.99,
    category: 'beverages',
    imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=300&h=300&fit=crop',
    inStock: true,
    tags: ['orange juice', 'sparkling', 'juice', 'beverages'],
  },
];

/**
 * Search products by query string and optional price filter.
 */
export function searchProducts(
  query: string,
  maxPrice?: number,
  filters: string[] = []
): Product[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);

  return MOCK_PRODUCTS.filter((product) => {
    // Price filter
    if (maxPrice !== undefined && product.price > maxPrice) return false;

    // Organic / filter keywords
    for (const f of filters) {
      if (!product.tags.includes(f) && !product.name.toLowerCase().includes(f)) {
        return false;
      }
    }

    // Text match across name, brand, tags
    const searchable = [
      product.name.toLowerCase(),
      product.brand.toLowerCase(),
      ...product.tags,
    ].join(' ');

    return terms.some((term) => searchable.includes(term));
  });
}
